import jsPDF from "jspdf";
import {
  type BoreholeEntry,
  type BoreholeProject,
  formatAS1726Description,
  formatDepthRange,
  formatTestResults,
  formatDCPResults,
  formatSPTResult,
} from "./as1726";

const MARGIN = 20;
const PAGE_W = 210; // A4
const PAGE_H = 297;
const CONTENT_W = PAGE_W - MARGIN * 2;

function drawHeader(doc: jsPDF, projectName: string, boreholeId: string) {
  // Title bar
  doc.setFillColor(30, 41, 35); // dark earth
  doc.rect(0, 0, PAGE_W, 32, "F");

  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("BOREHOLE LOG", MARGIN, 14);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("AS 1726:2017 — Geotechnical Site Investigations", MARGIN, 22);
  doc.text("Auto-Soil Logger", PAGE_W - MARGIN, 22, { align: "right" });

  // Meta row
  const metaY = 38;
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("Project:", MARGIN, metaY);
  doc.setFont("helvetica", "normal");
  doc.text(projectName || "—", MARGIN + 18, metaY);

  doc.setFont("helvetica", "bold");
  doc.text("Borehole:", PAGE_W / 2, metaY);
  doc.setFont("helvetica", "normal");
  doc.text(boreholeId || "—", PAGE_W / 2 + 22, metaY);

  const dateStr = new Date().toLocaleDateString("en-AU");
  doc.setFont("helvetica", "bold");
  doc.text("Date:", PAGE_W - MARGIN - 30, metaY);
  doc.setFont("helvetica", "normal");
  doc.text(dateStr, PAGE_W - MARGIN, metaY, { align: "right" });

  // Separator
  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, metaY + 4, PAGE_W - MARGIN, metaY + 4);

  return metaY + 10;
}

function drawTableHeader(doc: jsPDF, y: number): number {
  const cols = [
    { label: "Depth (m)", x: MARGIN, w: 28 },
    { label: "AS 1726 Description", x: MARGIN + 28, w: 82 },
    { label: "Test Results", x: MARGIN + 110, w: 45 },
    { label: "Grading", x: MARGIN + 155, w: CONTENT_W - 155 },
  ];

  doc.setFillColor(45, 60, 50);
  doc.rect(MARGIN, y, CONTENT_W, 8, "F");

  doc.setFontSize(7.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);

  cols.forEach((col) => {
    doc.text(col.label, col.x + 2, y + 5.5);
  });

  return y + 8;
}

function drawRow(doc: jsPDF, entry: BoreholeEntry, y: number, index: number): number {
  const description = formatAS1726Description(entry);
  const depthRange = formatDepthRange(entry);
  const testResults = formatTestResults(entry);

  // Wrap description text
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  const descLines = doc.splitTextToSize(description || "—", 78);
  const testLines = testResults.length > 0 ? testResults : ["—"];
  const rowHeight = Math.max(descLines.length * 4.5 + 4, testLines.length * 4.5 + 4, 12);

  // Check page break
  if (y + rowHeight > PAGE_H - 20) {
    doc.addPage();
    y = 20;
    y = drawTableHeader(doc, y);
  }

  // Alternating row background
  if (index % 2 === 0) {
    doc.setFillColor(245, 247, 244);
    doc.rect(MARGIN, y, CONTENT_W, rowHeight, "F");
  }

  // Grid lines
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, y + rowHeight, PAGE_W - MARGIN, y + rowHeight);
  // Vertical separators
  [28, 110, 155].forEach((offset) => {
    doc.line(MARGIN + offset, y, MARGIN + offset, y + rowHeight);
  });

  const textY = y + 5;
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(8);

  // Depth
  doc.setFont("helvetica", "bold");
  doc.text(depthRange || "—", MARGIN + 2, textY);

  // Description
  doc.setFont("helvetica", "normal");
  doc.text(descLines, MARGIN + 30, textY);

  // Test results
  doc.setFontSize(7);
  testLines.forEach((line, i) => {
    doc.text(line, MARGIN + 112, textY + i * 4.5);
  });

  // Grading
  doc.setFontSize(7);
  doc.text(entry.gradingSummary || "—", MARGIN + 157, textY);

  return y + rowHeight;
}

function drawFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Page ${i} of ${pageCount}  |  Generated by Auto-Soil Logger  |  AS 1726:2017`,
      PAGE_W / 2,
      PAGE_H - 8,
      { align: "center" }
    );
    // Bottom border
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, PAGE_H - 14, PAGE_W - MARGIN, PAGE_H - 14);
  }
}

export function generateBoreholeLogPDF(
  entries: BoreholeEntry[],
  projectName: string,
  boreholeId: string,
  project?: BoreholeProject
) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  let y = drawHeader(doc, projectName, boreholeId);
  y = drawTableHeader(doc, y);

  // Outer table border
  doc.setDrawColor(45, 60, 50);
  doc.setLineWidth(0.5);
  doc.rect(MARGIN, y - 8, CONTENT_W, 0.1, "S");

  entries.forEach((entry, i) => {
    y = drawRow(doc, entry, y, i);
  });

  // Close table bottom
  doc.setDrawColor(45, 60, 50);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);

  // Project-level in-situ test results
  if (project) {
    const sptStr = formatSPTResult(project as any);
    const dcpStr = formatDCPResults(project as any);
    if (sptStr || dcpStr) {
      y += 6;
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(40, 40, 40);
      doc.text("IN-SITU TESTING (BOREHOLE)", MARGIN, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      if (sptStr) { doc.text(sptStr, MARGIN, y); y += 4.5; }
      if (dcpStr) { doc.text(dcpStr, MARGIN, y); y += 4.5; }
    }
  }

  drawFooter(doc);

  const filename = `${projectName || "borehole"}_${boreholeId || "log"}.pdf`;
  doc.save(filename);
}
